Home PR
lazaronazareno/practicas-nubi pull request #1
Opened 2020-05-02 16:54 UTC by lazaronazareno

Sumario: 
Vista de la sección Home, sin responsive.
Añadí los botones como componentes

Tarjeta de Trello: 
https://trello.com/c/MtG3D1Vd

Screenshot;

![vista_home1](https://user-images.githubusercontent.com/57498171/80870162-15090480-8c7b-11ea-98dd-4841f72170ea.png)

2020-05-04 13:30 UTC, jmtov requested changes
¡Buen trabajo, Lázaro!

Te dejé unos comentarios en el código. Por favor revisa detalladamente los espaciados, indentaciones, declaraciones de clases y elementos de HTML. Además, hay algunos archivos que parece que no se están usando y generan algo de ruido.

También, asegúrate que la base de los PRs que creaste después de este apunten a la rama que es ya que al apuntar todos los PRs a development, todos tienen las mismas ~18.000 líneas de cambios lo que se hace difícil de revisar. Por favor, revisa los demás PRs, ajusta las bases y aprovecha para corregir también en ellos los espaciados, indentaciones, clases y elementos de HTML, con eso no habrá necesidad de hacer comentarios sobre cosas que ya revisamos. 👌

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/buttons/about/button.js
> +   <button className={styles.button}><p1 className={styles.text}>Ver más</p1></button>
Recuerda siempre usar tags apropiados para el contenido. `p1` no es un tag de HTML válido. Acá podrías dejar sólo el contenido del botón sin necesidad de hacer un wrapping adicional.
```suggestion
   <button className={styles.button}>Ver más</button>
```

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/buttons/about/styles.module.scss
> +.text{
Recuerda siempre dejar espacios entre las definiciones de los selectores. También recuerda los espacios entre el selector y la llave de apertura. Te dejo la [guía de estilos](https://google.github.io/styleguide/htmlcssguide.html) de CSS y HTML que usa Google para que puedas chusmear un poco cómo se acomoda el código en otras empresas.
```suggestion
}

.text {
```

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/buttons/register/button.js
> +   </div>
Ten en cuenta la indentación de los elementos. En el documento de [estandarizar código](https://docs.google.com/document/d/1gJ0gB1NkinQXyRe5dk71yMUYE8c6dupLc-lYQ0osSro/edit) te explica bien cómo configurar el VSCode para que se haga automático.
También ten en cuenta el comentario de los elementos de HTML.

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/buttons/register/styles.module.scss
> +  height: 6vh;
Procura definir un width y un height que no sea tan dependiente del tamaño de la pantalla. Si la pantalla es muy chica, este botón no se verá bien.

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/buttons/register/styles.module.scss
> +.text{
Esta clase no sería necesaria al aplicar los comentarios que te hice arriba.

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/buttons/video/button.js
> +     </button>
Ten en cuenta el comentario de las etiquetas de HTML inválidas. También ten en cuenta la indentación.

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/buttons/video/styles.module.scss
> +  height: 6vh;
Ten en cuenta el comentario de las dimensiones de los botones.

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/buttons/video/styles.module.scss
> +}
No sería necesario esto tampoco.

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/home/home.js
> +    </div>
Ten cuidado con la indentación de JSX, a simple vista no es sencillo ver qué elemento contiene qué elementos.

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/home/home.js
> +  return(
Ten en cuenta que usar los espacios adecuadamente mejora la legibilidad del código: 
```suggestion
  render() {
  return (
```

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/home/homeThree.js
> +      </div>
Indentación.

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/home/styles.module.scss
> +  width: 205vh;
¿Por qué este width tan ancho? Generaría un scroll enorme en la pantalla.

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/home/styles.module.scss
> +  width: 205vh;
Lo mismo acá.

2020-05-04 13:30 UTC, jmtov commented on nubi/src/components/home/styles.module.scss
> +.container{
En general, revisa las dimensiones de estos elementos, lo más probable es que se estén saliendo del contenedor principal y estén generando un scroll innecesario.

2020-05-04 13:30 UTC, jmtov commented on src/App.js
> +      </div>
?????

2020-05-04 21:31 UTC, lazaronazareno commented on nubi/src/components/home/styles.module.scss
> +.container{
Gracias por los comentarios! Ya pude redimensionar los tamaños y arregle todos los errores de indentacion e hice un cambio del background de home ya que antes no estaba la usando como tal sino que estaba aparte.

2020-05-06 00:56 UTC, jmtov requested changes
¡Muy bien con la configuración del linter y con la limpieza en el código! Ahora es mucho más legible todo y se entiende mucho mejor.

Te dejé unos comentarios más, así que por favor revísalos y avísame cuando estén listos para aprobarte el PR.

2020-05-06 00:56 UTC, jmtov commented on nubi/src/components/buttons/about/styles.module.scss
> +  background-color: #5481ff;
Como este color se repite en varias partes, te recomendaría crear una variable de CSS o de SASS para referenciarlo cuando lo necesites, con eso es más fácil centralizar los colores de la aplicación.

2020-05-06 00:56 UTC, jmtov commented on nubi/src/components/buttons/register/button.js
> +    <div className={styles.container}>
¿Es necesario este contenedor?

2020-05-06 00:56 UTC, jmtov commented on nubi/src/components/buttons/register/styles.module.scss
> +  background-color: #5481ff;
Usa la variable que te mencioné arriba.

2020-05-06 00:56 UTC, jmtov commented on nubi/src/components/buttons/video/styles.module.scss
> +  border-color: #5481ff;
Usa la variable mencionada arriba.

2020-05-06 00:56 UTC, jmtov commented on nubi/src/components/home/homeThree.js
> +function HomeThree() {
Recomiendo usar nombres que permitan identificar a los elementos. ¿Qué tal algo como `PayWithPaypalSection`? (Lo mismo para el nombre del archivo)

2020-05-06 00:56 UTC, jmtov commented on nubi/src/components/home/homeTwo.js
> +function HomeTwo() {
Recomendaría usar nombres que permitan identificar a los elementos. ¿Qué tal algo como `WithdrawFromPaypal`? (Lo mismo para el nombre del archivo)

2020-05-06 00:56 UTC, jmtov commented on nubi/src/components/home/styles.module.scss
> +  color: #5481ff;
Usa la variable mencionada arriba.

2020-05-06 00:56 UTC, jmtov commented on nubi/src/components/home/home.js
> +      <div className={styles.secondContainer}>
Como este es hijo del contenedor de arriba, recomiendo no llamarlo `secondContainer` ya que en realidad es el primer contenedor dentro del contenedor `container` y puede generar confusiones.

2020-05-06 00:56 UTC, jmtov commented on nubi/src/components/home/home.js
> +      <div className={styles.thirdContainer}>
Idem para lo de arriba, pero con `thirdContainer`.

2020-05-06 00:56 UTC, jmtov commented on nubi/src/components/home/styles.module.scss
> +  color:#214960;
Asigna este color también a variables de CSS o de SASS para que puedas usarlos después.

2020-05-06 08:20 UTC, lazaronazareno commented on nubi/src/components/home/styles.module.scss
> +  color:#214960;
Gracias por los comentarios! Cree un archivo de colores en una carpeta constants y lo importe en los scss e hice los cambios que me comentaste sobre los contenedores.

2020-05-08 15:05 UTC, jmtov approved these changes
¡Excelente trabajo! 💪

2020-05-08 19:45 UTC, merged