Calculadora PR
lazaronazareno/practicas-nubi pull request #2
Opened 2020-05-02 16:58 UTC by lazaronazareno

Sumario:
Vista de la sección calculadora sin el responsive.
No tiene comportamiento, solo es el maquetado.
Reutilice el button creado en la rama Home.

Tarjeta de Trello:
https://trello.com/c/Hm3tnrDx

Screenshot: 
![vista_calculadora1](https://user-images.githubusercontent.com/57498171/80870443-d5dbb300-8c7c-11ea-90e0-ccb941439f7a.png)

2020-05-08 15:33 UTC, jmtov requested changes

2020-05-08 15:33 UTC, jmtov commented on nubi/src/App.js
>  }
¿No debería devolver ambos componentes `App`? tipo
```
function App() {
  return (
    <>
      <Home />
      <Calculadora />
    </>
  );
}
```

2020-05-08 15:33 UTC, jmtov commented on nubi/src/App.js
>  }
El `<>` representa un [Fragmento](https://reactjs.org/docs/fragments.html).

2020-05-08 15:33 UTC, jmtov commented on nubi/src/components/calculadora/calculadora.js
> +            <label className={styles.subTitle}>RETIRO</label>
Recuerda usar el atributo `name` y `id` en los inputs y el atributo `htmlFor` en los labels.

2020-05-08 15:33 UTC, jmtov commented on nubi/src/styles.module.scss
> -}
Si no necesitas este archivo, podrías borrarlo.

2020-05-08 16:34 UTC, lazaronazareno commented on nubi/src/styles.module.scss
> -}
Ahi corregí lo que me marcaste, y agregue un div al contenedor de Home y Calculadora.

2020-05-09 02:39 UTC, jmtov approved these changes

2020-05-09 02:39 UTC, jmtov commented on nubi/src/components/calculadora/styles.module.scss
> +  opacity: 0.4;
Cuidado con los valores bajos de opacidad ya que pueden ser problemáticos por bajo contraste.

2020-05-09 02:40 UTC, jmtov commented on nubi/src/styles.module.scss
> -}
¡Excelente!

2020-05-10 11:40 UTC, merged