Header PR
lazaronazareno/practicas-nubi pull request #4
Opened 2020-05-02 17:05 UTC by lazaronazareno

Sumario:
Terminado el Header de la pagina, sin responsive.
Re utilización de los botones creados en la rama Home.
No tiene comportamiento.

Tarjeta de Trello: 
https://trello.com/c/7AeBOkpb

Screenshot:
![vista_header1](https://user-images.githubusercontent.com/57498171/80870614-fb1cf100-8c7d-11ea-9b07-cdb3acfd499a.png)

2020-05-08 16:06 UTC, jmtov requested changes
¡Excelente! 🥳

2020-05-08 16:06 UTC, jmtov commented on nubi/src/App.js
> +  return <Header />;
Ten en cuenta [este](https://github.com/lazaronazareno/practicas-nubi/pull/2/files#r422197900) comentario.

2020-05-08 16:06 UTC, jmtov commented on nubi/src/components/header/styles.module.scss
> +  top: 0;
¡Bieeeen! 🎉

2020-05-08 16:06 UTC, jmtov commented on nubi/src/styles.module.scss
> -.app {
Si no necesitas este archivo, bórralo.

2020-05-08 18:05 UTC, lazaronazareno commented on nubi/src/App.js
> +  return <Header />;
Listo, ya corregi eso. Gracias!

2020-05-09 02:43 UTC, jmtov approved these changes
Nice!

![laptop cat](https://user-images.githubusercontent.com/3473831/81461962-bd403100-9185-11ea-83fc-c16480005508.gif)

2020-05-09 02:43 UTC, jmtov commented on nubi/src/App.js
> +    </div>
Recuerda mantener las ramas actualizadas entre sí parar evitar conflictos después.

2020-05-10 11:55 UTC, merged